#!/usr/bin/env python3
"""Apple's accepted media dimensions, read from the one file that states them.

    from apple_specs import screenshot_sizes, preview_sizes, render_markdown

These numbers lived in seven places in this track — two scripts, three reference
documents and two SKILL.md files — and they had already drifted: 1290×2796 was filed
under 6.7" in one table and 6.9" in another. Apple says 6.9". Nobody could have caught
it by reading, because each copy is internally consistent and looks right; the only way
to see a disagreement between seven tables is to have one table.

`apple-specs.json` beside this file is that table. It carries the URL it came from and
the date it was last checked, because these change — an iPhone generation adds a size
roughly every year, and the honest thing a file can do is say how old it is.

Both halves are here so neither can drift from the other: `screenshot_sizes()` for the
scripts that validate files, `render_markdown()` for the reference documents, which are
generated by `render_specs.py` rather than maintained by hand.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SPECS = os.path.join(HERE, "apple-specs.json")


def load():
    with open(SPECS, encoding="utf-8") as f:
        return json.load(f)


def screenshot_sizes(platforms=None):
    """{(w, h): "label"} for every accepted screenshot size, both orientations.

    Landscape is derived rather than listed: Apple accepts the transpose of every
    portrait size, and writing both out doubled the table for no information.
    """
    d = load()["screenshots"]
    out = {}
    for platform, families in d.items():
        if platforms and platform not in platforms:
            continue
        for fam in families:
            label = f"{platform} {fam['family']}".strip()
            for w, h in fam["sizes"]:
                out[(w, h)] = label
                if w != h:
                    out[(h, w)] = label + " landscape"
    return out


def preview_sizes():
    """{(w, h): "label"} for App Preview videos."""
    out = {}
    for platform, sizes in load()["previews"].items():
        for w, h in sizes:
            out[(w, h)] = f"{platform} preview"
    return out


def cert_types():
    """[(prefix, what it is for)] — the certificate table both signing scripts read.

    It was written out in `apple_creds.py` and `diagnose_signing.py`, and the two had
    already worded three of the ten differently. Nothing depends on the wording, which
    is exactly why nobody would ever have reconciled them.
    """
    return [(c["prefix"], c["does"]) for c in load()["certificates"]["types"]]


def checked_on():
    d = load()
    return d.get("_checked", "?"), d.get("_source", "")


def render_markdown():
    """The reference tables, generated. What `render_specs.py` writes into the docs."""
    d = load()
    when, src = checked_on()
    L = [f"*Generated from `apple-specs.json`. Apple's source: {src}",
         f"Last checked against it: {when}. Do not edit this section by hand —",
         "edit the JSON and run `render_specs.py`.*", "",
         f"{d['_rules']}", ""]
    for platform, families in d["screenshots"].items():
        L.append(f"### {platform}")
        L.append("")
        L.append("| Family | Portrait sizes | Devices |")
        L.append("|---|---|---|")
        for fam in families:
            sizes = " · ".join(f"{w} × {h}" for w, h in fam["sizes"])
            L.append(f"| {fam['family']} | {sizes} | {fam['devices']} |")
        L.append("")
    L.append("**Landscape is the transpose of every size above**, and is accepted wherever")
    L.append("the portrait one is.")
    L.append("")
    L.append(d.get("_watch_note", ""))
    L.append("")
    L.append("### App Preview videos")
    L.append("")
    L.append("| Platform | Sizes |")
    L.append("|---|---|")
    for platform, sizes in d["previews"].items():
        L.append(f"| {platform} | " + " · ".join(f"{w} × {h}" for w, h in sizes) + " |")
    L.append("")
    L.append(d.get("_preview_rules", ""))
    return "\n".join(L).rstrip() + "\n"


if __name__ == "__main__":
    when, src = checked_on()
    s, p = screenshot_sizes(), preview_sizes()
    print(f"apple-specs.json — checked {when}")
    print(f"  {len(s)} screenshot dimensions (both orientations), {len(p)} preview dimensions")
    print(f"  source: {src}")
