#!/usr/bin/env bash
# Build a debug APK and run it on a connected Android device.
#
# Copy this into the app's repo beside its iOS counterpart, then adapt the two
# marked spots and translate the comments into the repo's own language — they
# explain decisions to whoever reads that repo next, which is not this skill.
#
# Everything else is derived from the project, so it does not go stale:
# the application id from build.gradle, the launcher activity from the manifest.
set -euo pipefail
cd "$(dirname "$0")"

# ── adapt: where the Android project lives, relative to this script ──────────
ANDROID_DIR="android"

# ── the JDK ─────────────────────────────────────────────────────────────────
# A machine whose default JDK is older than the project asks for fails with either
#   "Cannot find a Java installation ... {languageVersion=NN, ...}"   (toolchain)
#   "invalid source release: NN"                                      (compat)
# The first reads like a missing install and is not one.
#
# $JAVA_VERSION overrides; otherwise the version is read from the project's own
# toolchain declaration rather than assumed. This used to hardcode 21 and Android
# Studio's bundled JBR — right for one kind of project on one kind of machine, and
# wrong for a Linux CI runner or a project on a different toolchain.
JDK_WANTED="${JAVA_VERSION:-}"
if [ -z "$JDK_WANTED" ]; then
  JDK_WANTED=$(grep -rhoE 'languageVersion[^0-9]*([0-9]{2})|(sourceCompatibility|targetCompatibility|jvmTarget)[^0-9]*([0-9]{2})' \
                 "$ANDROID_DIR" --include='build.gradle' --include='build.gradle.kts' 2>/dev/null \
               | grep -oE '[0-9]{2}' | sort -rn | head -1)
fi
JDK_WANTED="${JDK_WANTED:-21}"

if [ -n "${JAVA_HOME:-}" ] && [ -x "${JAVA_HOME}/bin/java" ]; then
  :                                     # the caller chose one; do not second-guess it
elif J=$(/usr/libexec/java_home -v "$JDK_WANTED" 2>/dev/null); then
  export JAVA_HOME="$J"                 # macOS, any vendor
elif [ -x "/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java" ]; then
  export JAVA_HOME="/Applications/Android Studio.app/Contents/jbr/Contents/Home"
elif command -v javac >/dev/null 2>&1; then
  :                                     # something is on PATH; let Gradle judge it
else
  echo "No JDK $JDK_WANTED found. Install one, or set \$JAVA_HOME." >&2
  exit 1
fi

# ── adb ─────────────────────────────────────────────────────────────────────
ADB=$(command -v adb || echo "$HOME/Library/Android/sdk/platform-tools/adb")
[ -x "$ADB" ] || { echo "adb not found — Android SDK platform-tools missing." >&2; exit 1; }

# ── device ──────────────────────────────────────────────────────────────────
# A physical device wins over an emulator, and the fallback is announced.
# This is not tidiness: an emulator has reported foreground-service and battery
# behaviour that never happened on real hardware, and fixes were written to
# chase it. ANDROID_SERIAL overrides, so a device can be forced without editing.
if [ -n "${ANDROID_SERIAL:-}" ]; then
  SERIAL="$ANDROID_SERIAL"
else
  ATTACHED=$("$ADB" devices | awk '$2=="device"{print $1}')
  PHYS=$(printf '%s\n' "$ATTACHED" | grep -v '^emulator-' | head -1 || true)
  EMU=$(printf '%s\n' "$ATTACHED" | grep '^emulator-' | head -1 || true)
  SERIAL="${PHYS:-$EMU}"
  [ -n "$SERIAL" ] || { echo "No Android device connected." >&2; exit 1; }
  [ -n "$PHYS" ] || echo "No physical device — running on emulator $SERIAL."
fi
echo "Device: $SERIAL"

# ── read the app's own identity, rather than hard-coding it ─────────────────
# Groovy or Kotlin DSL: `build.gradle.kts` is the default for a project generated by
# any recent Android Studio, and reading only `build.gradle` meant this script could
# not identify a new native project at all.
GRADLE=""
for c in "$ANDROID_DIR/app/build.gradle" "$ANDROID_DIR/app/build.gradle.kts"; do
  [ -f "$c" ] && { GRADLE="$c"; break; }
done
[ -n "$GRADLE" ] || { echo "No app/build.gradle or app/build.gradle.kts under $ANDROID_DIR" >&2; exit 1; }
MANIFEST="$ANDROID_DIR/app/src/main/AndroidManifest.xml"
# Both DSLs, both spellings: `applicationId "x"` (Groovy) and `applicationId = "x"` (Kotlin).
PKG=$(sed -n 's/.*applicationId[ =]*"\([^"]*\)".*/\1/p' "$GRADLE" | head -1)
[ -n "$PKG" ] || PKG=$(sed -n 's/.*namespace[ =]*"\([^"]*\)".*/\1/p' "$GRADLE" | head -1)
# An activity may be written relative (`.MainActivity`) or fully qualified
# (`com.example.MainActivity`). Matching only the leading dot missed every project
# that writes it out, which is the common shape in a native app.
ACT=$(sed -n 's/.*android:name="\(\.[A-Za-z0-9_.]*Activity\)".*/\1/p' "$MANIFEST" | head -1)
[ -n "$ACT" ] || ACT=$(sed -n 's/.*android:name="\([A-Za-z][A-Za-z0-9_.]*Activity\)".*/\1/p' "$MANIFEST" | head -1)
[ -n "$PKG" ] && [ -n "$ACT" ] || { echo "Could not read package/activity from the project." >&2; exit 1; }

# ── build ───────────────────────────────────────────────────────────────────
# A native project builds straight from Gradle. For a HYBRID one (Capacitor, Cordova,
# any web shell) the web build and the sync come FIRST, and skipping either is the
# quietest failure here: Gradle builds an APK around whatever the assets folder last
# held, the install succeeds, and the app shows the previous UI — which reads as "my
# change did nothing", not as a missing step.
if compgen -G "capacitor.config.*" >/dev/null 2>&1; then
  npm run build                      # adapt: whatever this app's web build is
  npx cap sync android
elif [ -f "config.xml" ] && grep -q "cordova" config.xml 2>/dev/null; then
  npm run build 2>/dev/null || true
  npx cordova prepare android
fi
(cd "$ANDROID_DIR" && ./gradlew assembleDebug)

APK="$ANDROID_DIR/app/build/outputs/apk/debug/app-debug.apk"
"$ADB" -s "$SERIAL" install -r "$APK"
"$ADB" -s "$SERIAL" shell am start -n "$PKG/$ACT" >/dev/null
echo "Running on the device."
